export const rarities = {
    1: { label: 'Common', color: '#838383' },
    2: { label: 'Uncommon', color: '#29781e' },
    3: { label: 'Rare', color: '#1c60a4' },
    4: { label: 'Epic', color: '#8b24d1' },
    5: { label: 'Fabled', color: '#30d330' },
};

export const ancients = {
     1: { label: 'Siyalatas', multipliers: { hybrid: 1, idle: 40 } },
     2: { label: 'Fragsworth', multipliers: { hybrid: 1, idle: 1 } },
     3: { label: 'Chronos', multipliers: { hybrid: 30, idle: 20 } },
     4: { label: 'Chawedo', multipliers: { hybrid: 1, idle: 1 } },
     5: { label: 'Revolc', multipliers: { hybrid: 40, idle: 60 } },
     7: { label: 'Argaiv', multipliers: { hybrid: 1, idle: 40 } },
     8: { label: 'Energon', multipliers: { hybrid: 10, idle: 1 } },
     9: { label: 'Kleptos', multipliers: { hybrid: 15, idle: 1 } },
    10: { label: 'Sniperino', multipliers: { hybrid: 60, idle: 1 } },
    11: { label: 'Berserker', multipliers: { hybrid: 1, idle: 1 } },
    12: { label: 'Hecatoncheir', multipliers: { hybrid: 10, idle: 1 } },
    13: { label: 'Bubos', multipliers: { hybrid: 35, idle: 20 } },
    14: { label: 'Morgulis', multipliers: { hybrid: 1, idle: 1 } },
    15: { label: 'Bhaal', multipliers: { hybrid: 1, idle: 1 } },
    16: { label: 'Dora', multipliers: { hybrid: 55, idle: 50 } },
    17: { label: 'Atman', multipliers: { hybrid: 100, idle: 100 } },
    18: { label: 'Fortuna', multipliers: { hybrid: 45, idle: 50 } },
    19: { label: 'Dogcog', multipliers: { hybrid: 50, idle: 70 } },
    21: { label: 'Mimzee', multipliers: { hybrid: 1, idle: 30 } },
    22: { label: 'Mammon', multipliers: { hybrid: 1, idle: 40 } },
    24: { label: 'Libertas', multipliers: { hybrid: 1, idle: 1 } },
    25: { label: 'Solomon', multipliers: { hybrid: 1, idle: 80 } },
    26: { label: 'Juggernaut', multipliers: { hybrid: 1, idle: 1 } },
    27: { label: 'Kumawakamaru', multipliers: { hybrid: 100, idle: 100 } },
    28: { label: 'Vaagur', multipliers: { hybrid: 25, idle: 20 } },
};

export const heroes = {
    cid: { label: 'Cid, the Helpful Adventurer', baseCost: 5 },
    treebeast: { label: 'Treebeast', baseCost: 50 },
    ivan: { label: 'Ivan, the Drunken Brawler', baseCost: 250 },
    brittany: { label: 'Brittany, Beach Princess', baseCost: 1000 },
    fisherman: { label: 'The Wandering Fisherman', baseCost: 4000 },
    betty: { label: 'Betty Clicker', baseCost: 20000 },
    samurai: { label: 'The Masked Samurai', baseCost: 1.00e+05 },
    leon: { label: 'Leon', baseCost: 4.00e+05 },
    forest: { label: 'The Great Forest Seer', baseCost: 2.50e+06 },
    alexa: { label: 'Alexa, Assassin', baseCost: 1.50e+07 },
    natalia: { label: 'Natalia, Ice Apprentice', baseCost: 1.00e+08 },
    mercedes: { label: 'Mercedes, Duchess of Blades', baseCost: 8.00e+08 },
    bobby: { label: 'Bobby, Bounty Hunter', baseCost: 6.50e+09 },
    broyle: { label: 'Broyle Lindeoven, Fire Mage', baseCost: 5.00e+10 },
    george: { label: 'Sir George II, King\'s Guard', baseCost: 4.50e+11 },
    midas: { label: 'King Midas', baseCost: 4.00e+12 },
    referi: { label: 'Referi Jerator, Ice Wizard', baseCost: 3.60e+13 },
    abaddon: { label: 'Abaddon', baseCost: 3.20e+14 },
    mazhu: { label: 'Ma Zhu', baseCost: 2.70e+15 },
    amenhotep: { label: 'Amenhotep', baseCost: 2.40e+16 },
    beastlord: { label: 'Beastlord', baseCost: 3.00e+17 },
    athena: { label: 'Athena, Goddess of War', baseCost: 9.00e+18 },
    aphrodite: { label: 'Aphrodite, Goddess of Love', baseCost: 3.50e+20 },
    shinatobe: { label: 'Shinatobe, Wind Deity', baseCost: 1.40e+22 },
    grant: { label: 'Grant, the General', baseCost: 4.20e+24 },
    frostleaf: { label: 'Frostleaf', baseCost: 2.10e+27 },
    dreadKnight: { label: 'Dread Knight', baseCost: 1.00e+40 },
    atlas: { label: 'Atlas', baseCost: 1.00e+55 },
    terra: { label: 'Terra', baseCost: 1.00e+70 },
    phtalo: { label: 'Phthalo', baseCost: 1.00e+85 },
    orntchya: { label: 'Orntchya Gladeye, Didensy Banana', baseCost: 1.00e+100 },
    lillin: { label: 'Lilin', baseCost: 1.00e+115 },
    cadmia: { label: 'Cadmia', baseCost: 1.00e+130 },
    alabaster: { label: 'Alabaster', baseCost: 1.00e+145 },
    astraea: { label: 'Astraea', baseCost: 1.00e+160 },
    chiron: { label: 'Chiron', baseCost: 1.00e+175 },
    moloch: { label: 'Moloch', baseCost: 1.00e+190 },
    bomberMax: { label: 'Bomber Max', baseCost: 1.00e+205 },
    gog: { label: 'Gog', baseCost: 1.00e+220 },
    wepwawet: { label: 'Wepwawet', baseCost: 1.00e+235 },
    tsuchi: { label: 'Tsuchi', baseCost: 1.00e+500 },
    skogur: { label: 'Skogur', baseCost: 1.00e+1000 },
    moeru: { label: 'Moeru', baseCost: 1.00e+2000 },
    zilar: { label: 'Zilar', baseCost: 1.00e+4000 },
    madzi: { label: 'Madzi', baseCost: 1.00e+8000 },
};
