export const LOCALSTORAGE_KEY = 'adch-state';

export const rarities = {
    1: { label: 'Common', className: 'common' },
    2: { label: 'Uncommon', className: 'uncommon' },
    3: { label: 'Rare', className: 'rare' },
    4: { label: 'Epic', className: 'epic' },
    5: { label: 'Fabled', className: 'fabled' },
    6: { label: 'Mythical', className: 'mythical' },
    7: { label: 'Legendary', className: 'legendary' },
    8: { label: 'Transcendent', className: 'transcendent' },
};

export const heroes = {
    cid: { label: 'Cid, the Helpful Adventurer', baseCost: 5, newBaseCost: [5, 0]},
    treebeast: { label: 'Treebeast', baseCost: 50, newBaseCost: [5, 1]},
    ivan: { label: 'Ivan, the Drunken Brawler', baseCost: 250, newBaseCost: [2.5, 2]},
    brittany: { label: 'Brittany, Beach Princess', baseCost: 1000, newBaseCost: [1, 3]},
    fisherman: { label: 'The Wandering Fisherman', baseCost: 4000, newBaseCost: [4, 3]},
    betty: { label: 'Betty Clicker', baseCost: 20000, newBaseCost: [2, 4]},
    samurai: { label: 'The Masked Samurai', baseCost: 1.00e+05, newBaseCost: [1, 5]},
    leon: { label: 'Leon', baseCost: 4.00e+05, newBaseCost: [4, 5]},
    forest: { label: 'The Great Forest Seer', baseCost: 2.50e+06, newBaseCost: [2.5, 6]},
    alexa: { label: 'Alexa, Assassin', baseCost: 1.50e+07, newBaseCost: [1.5, 7]},
    natalia: { label: 'Natalia, Ice Apprentice', baseCost: 1.00e+08, newBaseCost: [1, 8]},
    mercedes: { label: 'Mercedes, Duchess of Blades', baseCost: 8.00e+08, newBaseCost: [8, 8]},
    bobby: { label: 'Bobby, Bounty Hunter', baseCost: 6.50e+09, newBaseCost: [6.5, 9]},
    broyle: { label: 'Broyle Lindeoven, Fire Mage', baseCost: 5.00e+10, newBaseCost: [5, 10]},
    george: { label: 'Sir George II, King\'s Guard', baseCost: 4.50e+11, newBaseCost: [4.5, 11]},
    midas: { label: 'King Midas', baseCost: 4.00e+12, newBaseCost: [4, 12]},
    referi: { label: 'Referi Jerator, Ice Wizard', baseCost: 3.60e+13, newBaseCost: [3.6, 13]},
    abaddon: { label: 'Abaddon', baseCost: 3.20e+14, newBaseCost: [3.2, 14]},
    mazhu: { label: 'Ma Zhu', baseCost: 2.70e+15, newBaseCost: [2.7, 15]},
    amenhotep: { label: 'Amenhotep', baseCost: 2.40e+16, newBaseCost: [2.4, 16]},
    beastlord: { label: 'Beastlord', baseCost: 3.00e+17, newBaseCost: [3, 17]},
    athena: { label: 'Athena, Goddess of War', baseCost: 9.00e+18, newBaseCost: [9, 18]},
    aphrodite: { label: 'Aphrodite, Goddess of Love', baseCost: 3.50e+20, newBaseCost: [3.5, 20]},
    shinatobe: { label: 'Shinatobe, Wind Deity', baseCost: 1.40e+22, newBaseCost: [1.4, 22]},
    grant: { label: 'Grant, the General', baseCost: 4.20e+24, newBaseCost: [4.2, 24]},
    frostleaf: { label: 'Frostleaf', baseCost: 2.10e+27, newBaseCost: [2.1, 27]},
    dreadKnight: { label: 'Dread Knight', baseCost: 1.00e+40, newBaseCost: [1, 40]},
    atlas: { label: 'Atlas', baseCost: 1.00e+55, newBaseCost: [1, 55]},
    terra: { label: 'Terra', baseCost: 1.00e+70, newBaseCost: [1, 70]},
    phtalo: { label: 'Phthalo', baseCost: 1.00e+85, newBaseCost: [1, 85]},
    orntchya: { label: 'Orntchya Gladeye, Didensy Banana', baseCost: 1.00e+100, newBaseCost: [1, 100]},
    lillin: { label: 'Lilin', baseCost: 1.00e+115, newBaseCost: [1, 115]},
    cadmia: { label: 'Cadmia', baseCost: 1.00e+130, newBaseCost: [1, 130]},
    alabaster: { label: 'Alabaster', baseCost: 1.00e+145, newBaseCost: [1, 145]},
    astraea: { label: 'Astraea', baseCost: 1.00e+160, newBaseCost: [1, 160]},
    chiron: { label: 'Chiron', baseCost: 1.00e+175, newBaseCost: [1, 175]},
    moloch: { label: 'Moloch', baseCost: 1.00e+190, newBaseCost: [1, 190]},
    bomberMax: { label: 'Bomber Max', baseCost: 1.00e+205, newBaseCost: [1, 205]},
    gog: { label: 'Gog', baseCost: 1.00e+220, newBaseCost: [1, 220]},
    wepwawet: { label: 'Wepwawet', baseCost: 1.00e+235, newBaseCost: [1, 235]},
    tsuchi: { label: 'Tsuchi', baseCost: 1.00e+500, newBaseCost: [1, 500]},
    skogur: { label: 'Skogur', baseCost: 1.00e+1000, newBaseCost: [1, 1000]},
    moeru: { label: 'Moeru', baseCost: 1.00e+2000, newBaseCost: [1, 2000]},
    zilar: { label: 'Zilar', baseCost: 1.00e+4000, newBaseCost: [1, 4000]},
    madzi: { label: 'Madzi', baseCost: 1.00e+8000, newBaseCost: [1, 8000]},
};

export const mercenaryQuests = {
    type: {
        1: 'Recruit new Mercenary',
        2: 'UNKNOWN',
        3: 'UNKNOWN',
        4: 'UNKNOWN',
        5: 'UNKNOWN',
        6: 'Rubies',
    },
    typeBaseReward: {
        1: 1,
        2: 1,
        3: 1,
        4: 1,
        5: 1,
        6: 0.267, // Rubies
    },
    stat: {
        1: 'Extra Gold',
        2: 'Extra Hero Souls',
        3: 'Extra Rubies',
        4: 'UNKNOWN',
        5: 'Extra Lives',
        6: 'UNKNOWN',
    },
    rewards: {
        Common: 5,
        Uncommon: 8,
        Rare: 10,
        Epic: 20,
        Fabled: 50,
        Mythical: 200,
        Legendary: 500,
        Transcendent: 2000,
    },
};
