export const LOCALSTORAGE_KEY = 'adch-state';

export const rarities = {
    1: { label: 'Common', className: 'common' },
    2: { label: 'Uncommon', className: 'uncommon' },
    3: { label: 'Rare', className: 'rare' },
    4: { label: 'Epic', className: 'epic' },
    5: { label: 'Fabled', className: 'fabled' },
    6: { label: 'Mythical', className: 'mythical' },
    7: { label: 'Legendary', className: 'legendary' },
    8: { label: 'Transcendent', className: 'transcendent' },
};

export const heroes = {
    cid: { label: 'Cid, the Helpful Adventurer', baseCost: 5 },
    treebeast: { label: 'Treebeast', baseCost: 50 },
    ivan: { label: 'Ivan, the Drunken Brawler', baseCost: 250 },
    brittany: { label: 'Brittany, Beach Princess', baseCost: 1000 },
    fisherman: { label: 'The Wandering Fisherman', baseCost: 4000 },
    betty: { label: 'Betty Clicker', baseCost: 20000 },
    samurai: { label: 'The Masked Samurai', baseCost: 1.0e5 },
    leon: { label: 'Leon', baseCost: 4.0e5 },
    forest: { label: 'The Great Forest Seer', baseCost: 2.5e6 },
    alexa: { label: 'Alexa, Assassin', baseCost: 1.5e7 },
    natalia: { label: 'Natalia, Ice Apprentice', baseCost: 1.0e8 },
    mercedes: { label: 'Mercedes, Duchess of Blades', baseCost: 8.0e8 },
    bobby: { label: 'Bobby, Bounty Hunter', baseCost: 6.5e9 },
    broyle: { label: 'Broyle Lindeoven, Fire Mage', baseCost: 5.0e10 },
    george: { label: "Sir George II, King's Guard", baseCost: 4.5e11 },
    midas: { label: 'King Midas', baseCost: 4.0e12 },
    referi: { label: 'Referi Jerator, Ice Wizard', baseCost: 3.6e13 },
    abaddon: { label: 'Abaddon', baseCost: 3.2e14 },
    mazhu: { label: 'Ma Zhu', baseCost: 2.7e15 },
    amenhotep: { label: 'Amenhotep', baseCost: 2.4e16 },
    beastlord: { label: 'Beastlord', baseCost: 3.0e17 },
    athena: { label: 'Athena, Goddess of War', baseCost: 9.0e18 },
    aphrodite: { label: 'Aphrodite, Goddess of Love', baseCost: 3.5e20 },
    shinatobe: { label: 'Shinatobe, Wind Deity', baseCost: 1.4e22 },
    grant: { label: 'Grant, the General', baseCost: 4.2e24 },
    frostleaf: { label: 'Frostleaf', baseCost: 2.1e27 },
    dreadKnight: { label: 'Dread Knight', baseCost: 1.0e40 },
    atlas: { label: 'Atlas', baseCost: 1.0e55 },
    terra: { label: 'Terra', baseCost: 1.0e70 },
    phtalo: { label: 'Phthalo', baseCost: 1.0e85 },
    orntchya: { label: 'Orntchya Gladeye, Didensy Banana', baseCost: 1.0e100 },
    lillin: { label: 'Lilin', baseCost: 1.0e115 },
    cadmia: { label: 'Cadmia', baseCost: 1.0e130 },
    alabaster: { label: 'Alabaster', baseCost: 1.0e145 },
    astraea: { label: 'Astraea', baseCost: 1.0e160 },
    chiron: { label: 'Chiron', baseCost: 1.0e175 },
    moloch: { label: 'Moloch', baseCost: 1.0e190 },
    bomberMax: { label: 'Bomber Max', baseCost: 1.0e205 },
    gog: { label: 'Gog', baseCost: 1.0e220 },
    wepwawet: { label: 'Wepwawet', baseCost: 1.0e235 },
    tsuchi: { label: 'Tsuchi', baseCost: 1.0e500 },
    skogur: { label: 'Skogur', baseCost: 1.0e1000 },
    moeru: { label: 'Moeru', baseCost: 1.0e2000 },
    zilar: { label: 'Zilar', baseCost: 1.0e4000 },
    madzi: { label: 'Madzi', baseCost: 1.0e8000 },
};
